export const SET_SEARCHED_PRODUCTS = "SET_SEARCHED_PRODUCTS";

export const SET_SEARCHED_PRODUCT = "SET_SEARCHED_PRODUCT";

export const SET_SEARCHED_CATEGORIES = "SET_SEARCHED_CATEGORIES";

export const SET_SEARCHED_PRODUCTS_X_CATEGORY = "SET_SEARCHED_PRODUCTS_X_CATEGORY";

export const SET_EQUIVALENCE = "SET_EQUIVALENCE";

export const SET_TERMOFUSION = "SET_TERMOFUSION";

export const SET_CONTACT = "SET_CONTACT";

export const SET_TIME_LIFE = "SET_TIME_LIFE";

export const SET_BENEFIT = "SET_BENEFIT";

export const POST_CONTACT_FORM = "POST_CONTACT_FORM";

export const GET_ITEMS_SEARCHED = "GET_ITEMS_SEARCHED";

export const SET_IS_CONNECTED = "SET_IS_CONNECTED";

export const POST_SUBSCRIBE_FORM = "POST_SUBSCRIBE_FORM";
