export const SET_SEARCHED_PRODUCTS = "SET_SEARCHED_PRODUCTS";

export const SET_SEARCHED_PRODUCT = "SET_SEARCHED_PRODUCT";

export const SET_SEARCHED_CATEGORIES = "SET_SEARCHED_CATEGORIES";

export const SET_SEARCHED_PRODUCTS_X_CATEGORY = "SET_SEARCHED_PRODUCTS_X_CATEGORY";

export const SET_EQUIVALENCE = "SET_EQUIVALENCE";

export const SET_TERMOFUSION = "SET_TERMOFUSION";
