export const SET_SEARCHED_PRODUCTS = "SET_SEARCHED_PRODUCTS";

export const SET_SEARCHED_CATEGORIES = "SET_SEARCHED_CATEGORIES";

export const SET_SEARCHED_PRODUCTS_X_CATEGORY = "SET_SEARCHED_PRODUCTS_X_CATEGORY";
